//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinesClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public string Date { get; set; }
        public string Player_Name1 { get; set; }
        public string Player_Name2 { get; set; }
        public string Player1_score { get; set; }
        public string Player2_score { get; set; }
        public string Winner { get; set; }
    }
}
