//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinesClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public double Percentage { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int Ties { get; set; }
        public int Participated_Games { get; set; }
    }
}
