//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinesClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class rightNowGame
    {
        public int nowId { get; set; }
        public string Time { get; set; }
        public string UserName1 { get; set; }
        public string UserName2 { get; set; }
    }
}
